name:
  controller: ControllerClassName
  action: ActionName

home:
  controller: Taf\Controllers\PageController
  action: getHome

contact:
  controller: Taf\Controllers\PageController
  action: getContact

logIn:
  controller: Taf\Controllers\PageController
  action: getLogIn

signIn:
  controller: Taf\Controllers\PageController
  action: getSignIn

signIn2:
  controller: Taf\Controllers\PageController
  action: getSignIn2

404:
  controller: Taf\Controllers\Error
  action: error404Action

userConnexion:
  controller: Taf\Controllers\UserController
  action: userConnection