name:
  controller: ControllerClassName
  action: ActionName

home:
  controller: Taf\Controllers\PageController
  action: getHome

contact:
  controller: Taf\Controllers\PageController
  action: getContact

getName:
  controller: Taf\Controllers\Hello
  action: nameAction

404:
  controller: Taf\Controllers\Error
  action: error404Action

userlist:
  controller: Taf\Controllers\UserController
  action: listAction